### ISSUE TITLE
prometheus缺少了grafana对应的文件能否提供下呢?

### ISSUE THREAD

**Issue by xiaosadexiaohai** [cnych/k8s-repo#1]
prometheus缺少了grafana对应的文件能否提供下呢?

**Comment by xiaosadexiaohai** [comment]
@cnych

**Comment by cnych** [comment]
@xiaosadexiaohai 是grafana的安装yaml文件还是dashboard的json文件？

**Comment by xiaosadexiaohai** [comment]
可以麻烦提供git提供的整套grafana yaml和dashboard的json

**Comment by xiaosadexiaohai** [comment]
你的旧的文章用的是namespace: class100-ops 这里的yaml用的是namespace: kube-ops 怕万一不一致 @cnych
